open! Core
open! Import

module Phi_builder : sig
  type 'a t = ('a * Llvm.llbasicblock) list -> 'a Codegen.t

  val llvalue : Llvm.llvalue t
end

(** [compile_conditional cond ~compile_true ~compile_false ~compile_phi] generates a branch
    based on the value of [i1] [cond], to either the code of [compile_true] or
    [compile_false], then generates a phi node to combine their values *)
val compile_conditional
  :  cond_i1:Llvm.llvalue
  -> compile_true:(unit -> 'a Codegen.t)
  -> compile_false:(unit -> 'a Codegen.t)
  -> phi_builder:'a Phi_builder.t
  -> 'a Codegen.t

(** [compile_switch case ~table ~compile_default ~compile_phi] builds a switch statement,
    branching on the valule of [case], to either a branch in [table], or the
    default. Each branch is given as [(tag, name, compile_branch)] where the
    code generated by [compile_branch] is jumped to if [case] matches [tag].
    The branch results are recombined with [compile_phi]. *)
val compile_switch
  :  Llvm.llvalue
  -> table:(Llvm.llvalue * string * (unit -> 'a Codegen.t)) list
  -> compile_default:(unit -> 'a Codegen.t)
  -> phi_builder:'a Phi_builder.t
  -> 'a Codegen.t
